#include "render/Renderer.hpp"

#include "render/Camera.hpp"
#include "render/Mesh.hpp"
#include "core/Log.hpp"

#include <bgfx/bgfx.h>
#include <glm/gtc/type_ptr.hpp>

// Generated by shaderc at build time (see cmake/Shaders.cmake), DX11 profile.
// Arrays are named <shader>_dxbc.
#include "dxbc/vs_mesh.sc.bin.h"
#include "dxbc/fs_mesh.sc.bin.h"

namespace macad::render {

    namespace {

        constexpr bgfx::ViewId kMainView = 0;

    } // namespace

    Renderer::~Renderer() { shutdown(); }

    bool Renderer::init(const NativeWindow& window, int width, int height) {
        if (m_initialized) {
            return true;
        }

        bgfx::Init init;
        // Forced to D3D11 for Milestone 1: we embed only the DX11 (s_5_0) shader
        // profile. Multi-backend selection arrives with multi-profile shaders.
        init.type = bgfx::RendererType::Direct3D11;
        init.platformData.nwh = window.nwh;
        init.platformData.ndt = window.ndt;
        init.resolution.width = static_cast<std::uint32_t>(width);
        init.resolution.height = static_cast<std::uint32_t>(height);
        init.resolution.reset = BGFX_RESET_VSYNC;

        if (!bgfx::init(init)) {
            MACAD_LOG_ERROR("bgfx::init failed");
            return false;
        }

        m_width = width;
        m_height = height;
        m_initialized = true;

        bgfx::setViewClear(kMainView, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH,
            0x202428ff, 1.0f, 0);
        bgfx::setViewRect(kMainView, 0, 0, static_cast<std::uint16_t>(width),
            static_cast<std::uint16_t>(height));

        if (!createProgram()) {
            MACAD_LOG_ERROR("Failed to create mesh shader program");
            return false;
        }

        MACAD_LOG_INFO("Renderer initialized: backend={}, {}x{}", backendName(),
            width, height);
        return true;
    }

    bool Renderer::createProgram() {
        bgfx::ShaderHandle vsh =
            bgfx::createShader(bgfx::makeRef(vs_mesh_dxbc, sizeof(vs_mesh_dxbc)));
        bgfx::ShaderHandle fsh =
            bgfx::createShader(bgfx::makeRef(fs_mesh_dxbc, sizeof(fs_mesh_dxbc)));
        if (!bgfx::isValid(vsh) || !bgfx::isValid(fsh)) {
            return false;
        }
        m_program = bgfx::createProgram(vsh, fsh, /*destroyShaders*/ true).idx;
        return m_program != bgfx::kInvalidHandle;
    }

    void Renderer::shutdown() {
        if (!m_initialized) {
            return;
        }
        if (m_program != bgfx::kInvalidHandle) {
            bgfx::destroy(bgfx::ProgramHandle{ m_program });
            m_program = bgfx::kInvalidHandle;
        }
        bgfx::shutdown();
        m_initialized = false;
    }

    void Renderer::reset(int width, int height) {
        if (!m_initialized || (width == m_width && height == m_height)) {
            m_width = width;
            m_height = height;
            return;
        }
        m_width = width;
        m_height = height;
        bgfx::reset(static_cast<std::uint32_t>(width),
            static_cast<std::uint32_t>(height), BGFX_RESET_VSYNC);
        bgfx::setViewRect(kMainView, 0, 0, static_cast<std::uint16_t>(width),
            static_cast<std::uint16_t>(height));
    }

    void Renderer::beginFrame(const Camera& camera) {
        const mat4 view = camera.viewMatrix();
        const mat4 proj = camera.projMatrix();
        bgfx::setViewTransform(kMainView, glm::value_ptr(view), glm::value_ptr(proj));
        bgfx::setViewRect(kMainView, 0, 0, static_cast<std::uint16_t>(m_width),
            static_cast<std::uint16_t>(m_height));
        bgfx::touch(kMainView);
    }

    void Renderer::drawMesh(const Mesh& mesh, const mat4& model) {
        if (!mesh.valid() || m_program == bgfx::kInvalidHandle) {
            return;
        }
        bgfx::setTransform(glm::value_ptr(model));
        mesh.setBuffers();
        bgfx::setState(BGFX_STATE_DEFAULT);
        bgfx::submit(kMainView, bgfx::ProgramHandle{ m_program });
    }

    void Renderer::endFrame() { bgfx::frame(); }

    const char* Renderer::backendName() const {
        return bgfx::getRendererName(bgfx::getRendererType());
    }

} // namespace macad::render
